/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuggestionsRouteImport } from './routes/suggestions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesIdRouteImport } from './routes/activities.$id'
import { Route as ApiPublicCronRefreshOrganizersRouteImport } from './routes/api/public/cron.refresh-organizers'
import { Route as ApiPublicCronRefreshMonitorsRouteImport } from './routes/api/public/cron.refresh-monitors'

const SuggestionsRoute = SuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesIdRoute = ActivitiesIdRouteImport.update({
  id: '/activities/$id',
  path: '/activities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRefreshOrganizersRoute =
  ApiPublicCronRefreshOrganizersRouteImport.update({
    id: '/api/public/cron/refresh-organizers',
    path: '/api/public/cron/refresh-organizers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRefreshMonitorsRoute =
  ApiPublicCronRefreshMonitorsRouteImport.update({
    id: '/api/public/cron/refresh-monitors',
    path: '/api/public/cron/refresh-monitors',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/playlists': typeof PlaylistsRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRoute
  '/activities/$id': typeof ActivitiesIdRoute
  '/api/public/cron/refresh-monitors': typeof ApiPublicCronRefreshMonitorsRoute
  '/api/public/cron/refresh-organizers': typeof ApiPublicCronRefreshOrganizersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/playlists': typeof PlaylistsRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRoute
  '/activities/$id': typeof ActivitiesIdRoute
  '/api/public/cron/refresh-monitors': typeof ApiPublicCronRefreshMonitorsRoute
  '/api/public/cron/refresh-organizers': typeof ApiPublicCronRefreshOrganizersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/playlists': typeof PlaylistsRoute
  '/settings': typeof SettingsRoute
  '/suggestions': typeof SuggestionsRoute
  '/activities/$id': typeof ActivitiesIdRoute
  '/api/public/cron/refresh-monitors': typeof ApiPublicCronRefreshMonitorsRoute
  '/api/public/cron/refresh-organizers': typeof ApiPublicCronRefreshOrganizersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/calendar'
    | '/chat'
    | '/playlists'
    | '/settings'
    | '/suggestions'
    | '/activities/$id'
    | '/api/public/cron/refresh-monitors'
    | '/api/public/cron/refresh-organizers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/calendar'
    | '/chat'
    | '/playlists'
    | '/settings'
    | '/suggestions'
    | '/activities/$id'
    | '/api/public/cron/refresh-monitors'
    | '/api/public/cron/refresh-organizers'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/calendar'
    | '/chat'
    | '/playlists'
    | '/settings'
    | '/suggestions'
    | '/activities/$id'
    | '/api/public/cron/refresh-monitors'
    | '/api/public/cron/refresh-organizers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  CalendarRoute: typeof CalendarRoute
  ChatRoute: typeof ChatRoute
  PlaylistsRoute: typeof PlaylistsRoute
  SettingsRoute: typeof SettingsRoute
  SuggestionsRoute: typeof SuggestionsRoute
  ActivitiesIdRoute: typeof ActivitiesIdRoute
  ApiPublicCronRefreshMonitorsRoute: typeof ApiPublicCronRefreshMonitorsRoute
  ApiPublicCronRefreshOrganizersRoute: typeof ApiPublicCronRefreshOrganizersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$id': {
      id: '/activities/$id'
      path: '/activities/$id'
      fullPath: '/activities/$id'
      preLoaderRoute: typeof ActivitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-organizers': {
      id: '/api/public/cron/refresh-organizers'
      path: '/api/public/cron/refresh-organizers'
      fullPath: '/api/public/cron/refresh-organizers'
      preLoaderRoute: typeof ApiPublicCronRefreshOrganizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/refresh-monitors': {
      id: '/api/public/cron/refresh-monitors'
      path: '/api/public/cron/refresh-monitors'
      fullPath: '/api/public/cron/refresh-monitors'
      preLoaderRoute: typeof ApiPublicCronRefreshMonitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  CalendarRoute: CalendarRoute,
  ChatRoute: ChatRoute,
  PlaylistsRoute: PlaylistsRoute,
  SettingsRoute: SettingsRoute,
  SuggestionsRoute: SuggestionsRoute,
  ActivitiesIdRoute: ActivitiesIdRoute,
  ApiPublicCronRefreshMonitorsRoute: ApiPublicCronRefreshMonitorsRoute,
  ApiPublicCronRefreshOrganizersRoute: ApiPublicCronRefreshOrganizersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
